// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TouchSystems.BAL.Models
{
    public partial class STXDBContext : DbContext
    {
        public STXDBContext(DbContextOptions<STXDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Ip2location> Ip2location { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Ip2location>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("IP2Location");

                entity.Property(e => e.CityName)
                    .IsRequired()
                    .HasMaxLength(128);

                entity.Property(e => e.CountryCode)
                    .IsRequired()
                    .HasMaxLength(2);

                entity.Property(e => e.CountryName)
                    .IsRequired()
                    .HasMaxLength(64);

                entity.Property(e => e.Ipfrom).HasColumnName("IPFrom");

                entity.Property(e => e.Ipto).HasColumnName("IPTo");

                entity.Property(e => e.RegionName)
                    .IsRequired()
                    .HasMaxLength(128);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}